### ISSUE TITLE
Show model grids as a wms layer

### ISSUE THREAD

**Issue by metanomy** [sci-wms/sci-wms#84] opened 2015-10-09 12:11 UTC
@geofishfl request to have a visual representation of the mesh of a given model. That way we could compare the mesh between models not just their data output. I've created a $100 bounty for this enhancement: https://www.bountysource.com/issues/27287264-show-model-grids-as-a-wms-layer

**Comment by kwilcox** [comment] 2015-10-26 15:54
Duplicate of #87, closing in favor of that

**Closed as completed by kwilcox** 2015-10-26 15:54 UTC
